### ISSUE TITLE
Test: extract the "stationary distribution" directly from the output of the classifier

### ISSUE THREAD

**Issue by NeonNeon** [Kalior/clustering-genomic-signatures#52]
Use the frequency of each context to generate some kind of "stationary distribution" for all contexts/transitions

**Comment by Kalior** [comment]
Done in [this branch](https://github.com/Kalior/clustering-genomic-signatures/tree/feature/state-probabilities) . Not sure how to proceed since the probabilities need some sort of normalisation. The results didn't improve when using this instead of transition probabilities.
